# Copyright (c) 2019 Patrick Diehl

version: 2
jobs:
    build:
        machine:
            image: ubuntu-2004:202008-01
        environment:
            IMAGE_FOLDER_NAME: Docker
            IMAGE_NAME: diehlpk/teaching:latest
        steps:
            - checkout
            - setup_remote_docker:
              version: 19.03.12
            - run:
                name: Building Docker Image
                command: |
                    docker build -t ${IMAGE_NAME} ${IMAGE_FOLDER_NAME}
                    docker images
            - deploy:
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
                        docker push ${IMAGE_NAME}
                        docker login docker.pkg.github.com --username diehlpk -p ${TOKEN}
                    fi
