From fedora:34
MAINTAINER Patrick Diehl <patrickdiehl@lsu.edu>

RUN dnf update -y
RUN dnf install hpx-devel cmake git gcc-c++ cppcheck texlive-qrcode texlive-endnotes texlive-tikzposter texlive-lastpage texlive-scheme-medium latexmk texlive-doclicense pandoc gnuplot texlive-beamerswitch impallari-raleway-fonts texlive-datetime2 -y 
