From fedora:33
MAINTAINER Patrick Diehl <patrickdiehl@lsu.edu>

RUN dnf update -y
RUN dnf install hpx-devel cmake git gcc-c++ cppcheck texlive-scheme-medium texlive-qrcode texlive-endnotes texlive-tikzposter texlive-lastpage latexmk texlive-doclicense pandoc gnuplot texlive-beamerswitch impallari-raleway-fonts texlive-datetime2 -y 
